"""make flashcard course_id nullable

Revision ID: f2dfddc72f28
Revises: c59a553eda01
Create Date: 2026-06-02 11:05:46.558835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dfddc72f28'
down_revision: Union[str, None] = 'c59a553eda01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
